### ISSUE TITLE
Requesting for apk

### ISSUE THREAD

**Issue by istack-robel** [NoelieChristyCatolin/istack_test_app#1]
Hi Noe,

This is Robel from iStack. We would like to request for an apk for this since my Flutter instance can't execute this repo. 
If it's possible, please add the apk on this repo as well.

Thanks!

**Comment by NoelieChristyCatolin** [comment]
Hi,

Here is the link for apk
https://drive.google.com/file/d/1p9p8twj1aMrEby_m0Lq6YqqFTGd7yWgf/view?usp=sharing

I also attached here my flutter envi if it helps.
<img width="644" alt="Screen Shot 2022-09-08 at 4 05 54 PM" src="https://user-images.githubusercontent.com/14065758/189069515-ea2c146d-af20-4fb8-b405-cc84ba23b20c.png">

**Comment by istack-robel** [comment]
Thank you!
